[package]
name = "clicky"
version = "0.1.0"
authors = ["Steven Shaw <steven@steshaw.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#
[dependencies]
gio = "0.8.0"
gtk = "0.8.0"

#[dependencies.gtk]
#version = "0.8.0"
#features = ["v3_16"]
