[workspace]

members = [
    "./bob",
    "./book",
    "./by-example",
    "./c2rust",
    "./crash/bouncy4",
    "./crash/clicky",
    "./crash/course",
    "./gigasecond",
    "./hello-world",
    "./intro",
    "./leap",
    "./misc",
    "./multiple-lifetimes",
    "./raindrops",
    "./enum-eg",
]
