[package]
name = "crash"
version = "0.1.0"
authors = ["Steven Shaw <steven@steshaw.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
futures = "0.3.1"
