#!/usr/bin/env bash

set -euo pipefail

cargo check --all-targets
cargo test --all-features
cargo bench
cargo clippy --all-targets --all-features -- -D warnings
cargo fmt -- --check
cargo build --release
