#!/usr/bin/env bash

set -euo pipefail

msg() {
  echo -e "\e[48;2;0;0;150m\e[38;2;255;255;255m  $*  \e[0m"
}

file=
if [[ $# -ne 0 ]]; then
  file=${1}; shift
elif [[ -n ${WATCHEXEC_WRITTEN_PATH:-} ]]; then
  file=${WATCHEXEC_WRITTEN_PATH}
elif [[ -n ${WATCHEXEC_CREATED_PATH:-} ]]; then
  file=${WATCHEXEC_CREATED_PATH:-}
elif [[ -n ${WATCHEXEC_RENAMED_PATH:-} ]]; then
  file=${WATCHEXEC_RENAMED_PATH:-}
fi

if [[ -n ${file:-} ]]; then
  base_file=$(basename "${file}")
  example=${base_file%.rs}
  clear
  msg "Running example ${example}"
  RUST_BACKTRACE=1 cargo run --example "${example}" "${@}"
fi
