#!/usr/bin/env bash

set -euo pipefail
${DEBUG:-}

g() {
  echo "Testing $*"
  "$@" | diff data/fizzbuzz.expected -
}

g fizzbuzz.js
g fizzbuzz.bash
g cargo run --quiet --example 01-kick-fizzbuzz-1

for n in {1..6}; do
  g cargo run --quiet --example 01-kick-fizzbuzz "${n}"
done
