[package]
name = "book"
version = "0.1.0"
authors = ["Steven Shaw <steven@steshaw.org>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
